# Generated by Django 5.2 on 2025-04-28 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=200)),
                ('is_cardio', models.BooleanField()),
                ('is_strength', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('percieved_difficulty', models.IntegerField()),
                ('percieved_performance', models.IntegerField()),
                ('activity_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitymeta')),
            ],
        ),
    ]
