# Generated by Django 5.2 on 2025-04-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymeta',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='activitystats',
            name='entry_comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activitystats',
            name='entry_name',
            field=models.CharField(default='Unnamed Activity', max_length=200),
        ),
    ]
