# Generated by Django 5.2 on 2025-04-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activitymeta_activity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('is_cardio', models.BooleanField()),
                ('is_strength', models.BooleanField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='activitystats',
            name='activity_meta',
        ),
        migrations.DeleteModel(
            name='ActivityMeta',
        ),
        migrations.DeleteModel(
            name='ActivityStats',
        ),
    ]
