# Generated by Django 5.2 on 2025-05-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='effort',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='performance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
