# Generated by Django 5.2 on 2025-05-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_remove_activitystats_activity_meta_and_more'),
        ('workouts', '0003_workout_workout_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_activity',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
    ]
